# Generated by Django 4.1.3 on 2022-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_item_categories_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='media/default_zgdqfn.png', upload_to='media/items/'),
        ),
    ]
