# Generated by Django 4.1.3 on 2022-11-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_order_item_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
