# Generated by Django 4.1.3 on 2022-11-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OD', 'Ordered'), ('PI', 'Paid'), ('CM', 'Cancelled'), ('CM', 'Completed')], default='OD', max_length=2),
        ),
    ]
