# Generated by Django 4.1.3 on 2022-11-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OD', 'Ordered'), ('PI', 'Paid'), ('CN', 'Cancelled'), ('CM', 'Completed')], default='OD', max_length=2),
        ),
    ]
