# Generated by Django 4.1.3 on 2022-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ordered_count',
            field=models.IntegerField(default=0),
        ),
    ]
