# Generated by Django 4.1.3 on 2022-11-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_item_ordered_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-ordered_count']},
        ),
    ]
