# Generated by Django 4.1.3 on 2022-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0015_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
