# Generated by Django 4.1.3 on 2022-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0016_alter_restaurant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="retired",
            field=models.BooleanField(default=False),
        ),
    ]
