# Generated by Django 4.1.3 on 2022-11-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0022_alter_category_name_alter_item_restaurant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                default=34,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
        ),
    ]
