# Generated by Django 4.1.3 on 2022-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0025_alter_restaurant_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
