# Generated by Django 4.1.3 on 2022-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0026_alter_restaurant_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("OD", "Ordered"),
                    ("PI", "Paid"),
                    ("CN", "Cancelled"),
                    ("CM", "Completed"),
                    ("PN", "Pending"),
                ],
                default="PN",
                max_length=2,
            ),
        ),
    ]
