# Generated by Django 4.1.3 on 2022-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0027_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="datetime_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
