# Generated by Django 4.1.3 on 2022-11-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0028_order_datetime_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurants.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_price", models.IntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="restaurants.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="restaurants.order",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
    model_name='order',
    name='items',
),
migrations.AddField(
    model_name='order',
    name='items',
       field=models.ManyToManyField(
                related_name="orders",
                through="restaurants.OrderItem",
                to="restaurants.item",
            ),
)
    ]
