# Generated by Django 4.1.3 on 2022-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0029_alter_order_restaurant_alter_restaurant_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
