# Generated by Django 4.1.3 on 2022-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_display_picture_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='display_picture',
            field=models.ImageField(blank=True, default='media/person_default_ddlbql', null=True, upload_to='media/items/'),
        ),
    ]
