# Generated by Django 4.1.3 on 2022-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default='anonymoususer', max_length=32, null=True, unique=True, verbose_name='Username'),
        ),
    ]
