# Generated by Django 4.1.3 on 2022-11-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
