# Generated by Django 4.1.3 on 2022-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default='anonymoususer', max_length=32, null=True, verbose_name='Username'),
        ),
    ]
