# Generated by Django 4.1.3 on 2022-11-18 10:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="cart",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=255), size=None
                ),
                size=None,
            ),
        ),
    ]
