# Generated by Django 4.1.3 on 2022-11-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_alter_session_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
